export async function analyzeCodeQuality(code, language) {
  // Mocked analysis: simulate network latency and return a plausibly-structured report
  await new Promise((res) => setTimeout(res, 900))

  // Simple heuristics for demo purposes
  const plagiarismScore = Math.min(100, Math.floor(Math.random() * 40))
  const isAIContent = /def\s|class\s|return\s/.test(code) && Math.random() > 0.6

  return {
    plagiarismScore,
    isAIContent,
    reasoning: isAIContent
      ? 'Pattern analysis detected tropes and token sequences commonly generated by LLMs. Suggest manual review.'
      : 'Code appears human-written based on style markers and idiosyncratic naming.'
  }
}
